name = "julienne"
version = "2.0.1"
license = "license"
author = "Dan Bonachea, Damian Rouson, Brad Richardson, Patrick Raynaud, Katherine Rasmussen"
maintainer = "rouson@lbl.gov"
copyright = "Copyright 2024-2025, Sourcery Institute and Berkeley Lab"

[install]
library = true
