name = "julienne"
version = "1.5.3"
license = "license"
author = "Damian Rouson, Brad Richardson, Patrick Raynaud, Katherine Rasmussen"
maintainer = "rouson@lbl.gov"
copyright = "Copyright 2024, Sourcery Institute and Berkeley Lab"

[dependencies]
assert = {git = "https://github.com/berkeleylab/assert", tag = "2.0.1"}

[install]
library = true
