co_characterize – Julienne
co_characterize Module Procedure
33 statements
Source File
module procedure co_characterize module subroutine co_characterize(self) Interface →
Arguments
Type Intent Optional Attributes Name
class(test_result_t), intent(inout) :: self
Calls
Call graph
co_characterize calls call_julienne_assert, diagnostics_string, internal_co_sum_integer, internal_num_images, internal_sync_all, internal_this_image, test_passed, string