get_real – Julienne
get_real Module Procedure
15 statements
Source File
module procedure get_real pure module function get_real(self, key, mold) result(value_) Interface →
Arguments
Type Intent Optional Attributes Name
class(string_t), intent(in) :: self
class(string_t), intent(in) :: key
real, intent(in) :: mold
Return Value real
Calls
Call graph
get_real calls call_julienne_assert, get_json_key, string