get_logical – Julienne
get_logical Module Procedure
16 statements
Source File
module procedure get_logical pure module function get_logical(self, key, mold) result(value_) Interface →
Arguments
Type Intent Optional Attributes Name
class(string_t), intent(in) :: self
class(string_t), intent(in) :: key
logical, intent(in) :: mold
Return Value logical
Calls
Call graph
get_logical calls call_assert, call_julienne_assert, get_json_key, string