internal_this_image – Julienne
internal_this_image Module Procedure
10 statements
Source File
module procedure internal_this_image module function internal_this_image() result(this_image_id) Interface →
Arguments
None
Return Value integer
Calls
Call graph
internal_this_image calls call_assert, internal_num_images, julienne_this_image