internal_co_sum_integer – Julienne
internal_co_sum_integer Module Procedure
12 statements
Source File
module procedure internal_co_sum_integer module subroutine internal_co_sum_integer(a, result_image) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), target :: a(:)
integer, intent(in), optional :: result_image
Calls
Call graph
internal_co_sum_integer calls call_assert, internal_num_images, julienne_co_sum_integer