julienne_assert – Julienne
julienne_assert Module Procedure
7 statements
Source File
module procedure julienne_assert pure module subroutine julienne_assert(test_diagnosis, file, line)
Arguments
Type Intent Optional Attributes Name
type(test_diagnosis_t), intent(in) :: test_diagnosis
character(len=*), intent(in), optional :: file
integer, intent(in), optional :: line
Calls
Call graph
julienne_assert calls assert_always, diagnostics_string, test_passed, string