report – Julienne
report Module Procedure
70 statements
Source File
module procedure report module subroutine report(test, passes, tests, skips) Interface →
Arguments
Type Intent Optional Attributes Name
class(test_t), intent(in) :: test
integer, intent(inout) :: passes
integer, intent(inout) :: tests
integer, intent(inout) :: skips
Calls
Call graph
report calls characterize, flag_value, co_all, passed, passing_tests, results, skipped, skipped_tests, subject, test_results