report_results – Julienne
report_results Module Procedure
19 statements
Source File
module procedure report_results module subroutine report_results(self) Interface →
Arguments
Type Intent Optional Attributes Name
class(test_harness_t), intent(in) :: self
Calls
Call graph
report_results calls one_image_prints, report, print_usage_info_and_stop_if_requested
print_usage_info_and_stop_if_requested calls one_image_prints, argument_present