results – Julienne
results Function
32 statements
Source File
private function results() result(test_results)
Type Bound
scalar_and_vector_test_description_test_t
Arguments
None
Return Value type(test_result_t), allocatable, (:)
Calls
Call graph
results calls description_contains, contains_text, subject, run