results – Julienne
results Function
13 statements
Source File
private function results() result(test_results)
Type Bound
specimen_test_t
Arguments
None
Return Value type(test_result_t), allocatable, (:)
Calls
Call graph
results calls contains_text, subject, run