run – Julienne
run Module Procedure
5 statements
Source File
module procedure run module function run(test, test_descriptions) result(test_results) Interface →
Arguments
Type Intent Optional Attributes Name
class(test_t), intent(in) :: test
type(test_description_t), intent(in) :: test_descriptions(:)
Return Value type(test_result_t), allocatable, (:)
Calls
Call graph
run calls filter, run, subject