string_argument_present – Julienne
string_argument_present Module Procedure
25 statements
Source File
module procedure string_argument_present module function string_argument_present(acceptable_argument) result(found) Interface →
Arguments
Type Intent Optional Attributes Name
type(string_t), intent(in) :: acceptable_argument(:)
Return Value logical
Calls
Call graph
string_argument_present calls character_argument_present, string, strings