write_driver – Julienne
write_driver Module Procedure
34 statements
Source File
module procedure write_driver module subroutine write_driver(self, file_name) Interface →
Arguments
Type Intent Optional Attributes Name
class(test_suite_t), intent(in) :: self
character(len=*), intent(in) :: file_name
Calls
Call graph
write_driver calls test_modules, test_types, string