argument_present – Julienne
argument_present Interface
12 statements
Source File
interface
Called by
private module function argument_present(acceptable_argument) result(found) Implementation →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: acceptable_argument(:)
sample list: [character(len=len()):: "--benchmark", "-b", "/benchmark", "/b"] where dashes support Linux/macOS, slashes support Windows, and must be replaced by the longest list element ("--benchmark" above)
Return Value logical
Description
result is .true. only if a command-line argument matches an element of this function's argument
Call graph
help_requested calls argument_present
print_usage_info_and_stop_if_requested calls argument_present
check_for_command_line_argument calls argument_present
report_results calls print_usage_info_and_stop_if_requested
scaffold calls help_requested