as_character – Julienne
as_character Interface
224 statements
Source File
interface
Called by
private pure module function as_character(self) result(raw_string) Implementation →
Arguments
Type Intent Optional Attributes Name
class(string_t), intent(in) :: self
Return Value character(len=:),allocatable
Call graph
aggregate_diagnosis calls string
alphabetical_character_vs_string calls string
alphabetical_string_vs_character calls string
alphabetical_string_vs_string calls string
assign_string_t_to_character calls string
base_name calls string
character_eq_string_t calls string
character_ne_string_t calls string
character_stop_code calls string
co_characterize calls string
concatenate_elements calls string
contains_string_t calls string
description_contains_characters calls string
description_contains_string calls string
file_extension calls string
from_file_with_string_name calls string
get_double_precision calls string
get_double_precision_array calls string
get_integer calls string
get_json_key calls string
get_logical calls string
get_real calls string
get_real_array calls string
get_string_t_array_with_character_key calls string
get_string_t_array_with_string_t_key calls string
get_string_with_string_key calls string
string_argument_present calls string
string_flag_value calls string
string_t_eq_character calls string
string_t_eq_string_t calls string
string_t_ne_character calls string
string_t_ne_string_t calls string
write_to_character_file_name calls string
write_to_output_unit calls string
write_to_string_file_name calls string