contains_characters – Julienne
contains_characters Interface
24 statements
Source File
interface
Called by
private elemental module function contains_characters(self, substring) result(match) Implementation →
Arguments
Type Intent Optional Attributes Name
class(test_description_t), intent(in) :: self
character(len=*), intent(in) :: substring
Return Value logical
Description
The result is .true. if the test description includes the value of substring
Call graph
check_substring_search calls contains_text
results calls contains_text