flag_value – Julienne
flag_value Interface
12 statements
Source File
interface
Called by
private module function flag_value(flag) Implementation →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: flag
Return Value character(len=:),allocatable
Description
result = { the value passed immediately after a command-line flag if the flag is present or { an empty string otherwise.
Call graph
filter calls flag_value
print_usage_info_and_stop_if_requested calls flag_value
get_command_line_flag_value calls flag_value
scaffold calls flag_value
report_results calls print_usage_info_and_stop_if_requested