main – Julienne
main Program
33 statements
Source File
Uses
specimen_test_m
julienne_m
Example test main program to demonstrate the printing of diagnostic output when a test fails
Calls
Variables
Type Attributes Name Initial
integer :: passes = 0
type(specimen_test_t) :: specimen_test
integer :: tests = 0
Subroutines
subroutine print_usage_and_stop_if_help_requested()
Arguments
None
subroutine report_tally_and_error_stop_if_test_fails()
Arguments
None
Call graph
main calls report, print_usage_and_stop_if_help_requested, report_tally_and_error_stop_if_test_fails
print_usage_and_stop_if_help_requested calls argument_present